# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  commander:
    image: commander
    build:
      context: .
      dockerfile: Commander/Dockerfile
    ports:
      - 80
