# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3'

services:
  commander-backend:
    container_name: commander-backend
    build:
      context: .
      dockerfile: Commander/Dockerfile
    ports:
      - "5000:80"
    environment:
      ASPNETCORE_URLS: "http://+"
      ASPNETCORE_HTTPS_PORT: "5000"
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
    depends_on: 
      - mssql
    command: 
      - "sleep 5;" 

  commander-frontend:
    tty: true
    container_name: commander-frontend
    build:
      context: ./commander-frontend
      dockerfile: Dockerfile
    ports: 
      - "3001:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
      - NODE_ENV=development  
    depends_on: 
      - commander-backend

  mssql:
    container_name: mssql
    build:
      context: ./Database
      dockerfile: Dockerfile
    user: root
    environment:
      "ACCEPT_EULA": "Y"
      "SA_PASSWORD": "${MSSQL_PASSWORD}"
    ports:  
      - ${MSSQL_PORT:-1433}:1433
    volumes: 
      - ${MSSQL_DATA_DIR}:/var/opt/sqlserver/data
      - ${MSSQL_LOG_DIR}:/var/opt/sqlserver/log
      - ${MSSQL_BACKUP_DIR}:/var/opt/sqlserver/backup
    healthcheck:
      test: ['CMD', '/opt/mssql-tools/bin/sqlcmd', '-U', 'sa', '-P', '${MSSQL_PASSWORD}', '-Q', 'select 1']
      interval: 10s
      timeout: 3s
      retries: 2
